export const START_GET_POKEMONS = "START_GET_POKEMONS";
export const SUCCESS_GET_POKEMONS = "SUCCESS_GET_POKEMONS";
export const FAIL_GET_POKEMONS = "FAIL_GET_POKEMONS";

export const START_GET_POKEMON = "START_GET_POKEMON";
export const SUCCESS_GET_POKEMON = "SUCCESS_GET_POKEMON";
export const FAIL_GET_POKEMON = "FAIL_GET_POKEMON";
export const HANDLE_RETURN = "HANDLE_RETURN";
